### ISSUE TITLE
changing the input to USB

### ISSUE THREAD

**Issue by jazzo425** [kanishkaganguly/AmbientLighting#1]
I am trying to make a ambient lighting system for my computer and I have some led strip lights which plug into the computer via USB I was wondering if you could help me change to output to USB
thank you
Jazzo

**Comment by kanishkaganguly** [comment]
I am using an API directly, for the TP-Link bulb. The USB method might require some sort of API to communicate with the LEDs. Do you control the LEDs using some software by default or are they static colors?

**Comment by jazzo425** [comment]
I am using a led strip light which uses pre-set light controllable by a remote
thanks for replying

**Comment by kanishkaganguly** [comment]
Well, if it is remote controlled, then the only option would be to use a microcontroller (assuming it's an IR remote) to simulate the commands of the remote, and use that to send color values to the LED strip.
It shouldn't be hard to do, but requires external hardware and some extra code.

**Comment by jazzo425** [comment]
ok thanks could you suggest where to get either the tp-link bulb or the microcontroller

**Comment by kanishkaganguly** [comment]
Both are available on Amazon, depending on your location.
Here's a link to the [IRremote library](https://www.arduino.cc/reference/en/libraries/irremote/) and the [IR sensor](https://medium.com/illumination/arduino-with-infrared-sensor-48ad4415f320).

**Comment by jazzo425** [comment]
ok thanks
